* Qubes Admin Tools
A collection of scripts that is useful in Qubes OS.
** Usage Demo
The directory names indicate the place where scripts should be run.
*** dom0
**** myupdate
myupdate auto-updates all the VMs specified as command line arguments.
line. Example usage:
#+BEGIN_SRC shell
  bash myupdate fedora-26 debian-8 whonix-gw whonix-ws
#+END_SRC
**** mykillexcept
mykillexcept will shutdown all the VMs except those VMs specified as
command line arguments.

One useful example is shutting down all the VMs before shutting down
Qubes OS. This will accelarate the shutdown speed:
#+BEGIN_SRC shell
  bash mykillexcept
#+END_SRC

Another example is shutting down every running VMs except the critical
ones.
#+BEGIN_SRC shell
  bash mykillexcept sys-net sys-firewall sys-usb
#+END_SRC

*** AppVM
** Contribution
Qubes Admin Tools are all free softwares licensed under GPLv3. If you
find it helpful, please consider make it even more useful.

*** Propose New idea
Is there a tool that is nice to have? Just open an issue for your
proposal.
*** Contribute Code
You can either pull your own tools or work on existing the open issues.
*** Documents
What Qubes Admin Tools do you usually? Write an example for the
document.
