#!/bin/bash

selected_vms=()

function select-vm() {
    for vm in "$@"; do
        # TODO: determine how to support regex
        temp_vm_list=$(qvm-ls --raw-list 2>/dev/null | grep -E "$vm")
        for temp_vm in $temp_vm_list; do
            qvm-check "$temp_vm"
            if [[ $? -eq 0 ]]; then
                selected_vms+=("$temp_vm")
            fi
        done
    done
}

function shut-vm() {
    echo "${selected_vms[@]}"
    for vm in "${selected_vms[@]}"
    do
        echo "[*] Shutting down $vm..."
        exclude="${exclude} --exclude $vm"
    done
    eval "qvm-run 'sudo poweroff' --all $exclude"
}

if grep -q "R4" /etc/fedora-release; then
    select-vm "$@"
    shut-vm
elif grep -q "R3" /etc/fedora-release; then
    echo "[x] Qubes 3 is not supported."
else
    echo "[x] Qubes version is unkown."
fi
