#!/bin/bash

for vm in "$@"
do
  echo "[*] Updating $vm..."
  qvm-check $vm
  if [[ $? -eq 0 ]]; then
    qvm-run --auto $vm "if [ -f /etc/fedora-release ]; then sudo dnf update -y; elif [ -f /etc/debian_version ]; then sudo apt-get update && sudo apt-get upgrade -y; fi; sudo shutdown -h now"
  fi
done
